name: dart_html_utils
description: Miscellaneous utility code for Dart for the Web.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dartbag: ^0.6.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.16.0
