name: dart_html_utils
description: Miscellaneous utility code for Dart for the Web.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dartbag: ^0.8.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.16.0
